add examples for lang redirections
sebader/teams-distributor pull request #5
Opened 2021-03-17 14:17 UTC by timoleo23

Hi @sebader , I added an example to create the string to redirect based on language

2021-03-17 14:31 UTC, sebader requested changes

2021-03-17 14:31 UTC, sebader commented on README.md
> +backends="en=https://URL_EN_1;https://URL_EN_2,fr=https://URL_FR_1;https://URL_FR_2;https://URL_FR_3,de=https://URL_GE_1"
can you put it in ticks so it gets rendered nicely?

`backends="en=https://URL_EN_1;https://URL_EN_2,fr=https://URL_FR_1;https://URL_FR_2;https://URL_FR_3,de=https://URL_GE_1"`

2021-03-17 14:31 UTC, sebader commented on README.md
> +- For **English (en)**, you need to redirect users to URL's **https://URL_EN_1** and **https://URL_EN_2**
maybe put english last (after french and german) as it is also the fallback

2021-03-17 14:31 UTC, sebader commented on README.md
> +- For **French (fr)**, you need to redirect users to URL's **https://URL_FR_1**, **https://URL_FR_2** and **https://URL_FR_3**
maybe something like 

 For **French (fr)**, you have the following three URLs to to redirect and load balance users to:

2021-03-17 14:31 UTC, sebader commented on README.md
> +- For **German (de)**, you need to redirect userd to URL's **https://URL_GE_1**
typo userd

2021-03-17 14:31 UTC, sebader commented on README.md
> +Note: all other languages, not specified inthe backends definition, will fall into "en" as a default.
typo inthe

2021-03-18 08:30 UTC, timoleo23 commented
Changes commited

2021-03-18 08:37 UTC, sebader requested changes

2021-03-18 08:37 UTC, sebader commented on README.md
> +- For **German (de)**, you have the following URL to redirect and load balance users to: **https://URL_GE_1**
well, technically now for German you don't have anything to load balance ;)
So maybe just say 

For **German (de)**, you have the following single URL to redirect users to: **https://URL_GE_1**

2021-03-18 08:38 UTC, sebader requested changes

2021-03-18 08:38 UTC, sebader commented on README.md
>  az deployment group create -g  myresource-group --template-file .\main.json -p prefix=myprefix -p locationSecondary=westeurope -p loadBalancingMode=userLanguage -p backends="de=https://teams.microsof
ah, and can you update this example to use your URLs from above? thanks!

2021-03-19 09:39 UTC, timoleo23 commented
changes commited

2021-03-19 10:32 UTC, sebader approved these changes
beautiful! thanks so much for your contribution

2021-03-19 10:32 UTC, merged